language: node_js
node_js:
  - "6"
  - "5"
  - "4"
env:
  - DEPLOY_VERSION=testing
before_install:
  - "npm config set spin false"
  - "node . install -g ."
  - "mkdir -p /var/run/couchdb"
sudo: false
script: "npm test"
notifications:
    # slack: npm-inc:kRqQjto7YbINqHPb1X6nS3g8
